services:
  uptime-kuma:
    image: louislam/uptime-kuma
    pull_policy: always
    container_name: "${CONTAINER_NAME}"
    volumes:
      - "${UPTIME_KUMA_CONFIG}:/app/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "${KUMA_PORT}:3001"  # <Host Port>:<Container Port>
    restart: always