services:
  prometheus:
    image: prom/prometheus
    pull_policy: always
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - "${PROMETHEUS_CONFIG}:/etc/prometheus"
      - "${PROMETHEUS_DATA}:/prometheus"
