services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    pull_policy: always
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: always
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - "${NODE_EXPORTER_PORT}:9100"
