services:
  grafana:
    image: grafana/grafana:latest
    pull_policy: always
    container_name: grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - "${GRAFANA_CONFIG}:/var/lib/grafana"
