---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: "${CONTAINER_NAME}"
    pull_policy: always
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - "TZ=${TIMEZONE}"
    volumes:
      - "${JELLYFIN_CONFIG}:/config"
      - "${JELLYFIN_MEDIA_MOUNT}:/media_mnt:ro"
    ports:
      - "${JELLYFIN_WEB_PORT}:8096"
      - "${JELLYFIN_LOCAL_PORT}:7359/udp"
      - "${JELLYFIN_DNLA_PORT}:1900/udp"
      