services:
  audiobooks-setup:
    build: ./build/
    image: audiobooks-setup
    pull_policy: build
    container_name: audiobooks-setup
    env_file:
      - ./private/.env

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    pull_policy: always
    container_name: "audiobooks-qbittorrent"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=${TIMEZONE}"
      - "WEBUI_PORT=8080"
    restart: always
    ports:
      - "${AUDIOBOOKS_PORT}:8080"
    volumes:
      - "${AUDIOBOOKS_CONFIG}:/config"
      - "${AUDIOBOOKS_DOWNLOADS}:/downloads"
    #depends_on:
    #  audiobooks-setup:
    #    condition: service_completed_successfully
