---
services:
  portainer-setup:
    build: ./build/
    image: portainer-setup
    pull_policy: build
    container_name: "${SETUP_CONTAINER_NAME}"
    volumes:
      - "${PORTAINER_SSL}:/ssl"

  portainer:
    container_name: "${CONTAINER_NAME}"
    image: portainer/portainer-ce:latest
    pull_policy: always
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
      - "443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PORTAINER_CONFIG}:/data"
      - "${PORTAINER_SSL}:/certs"
    command: --ssl --sslcert /certs/portainer.crt --sslkey /certs/portainer.key
    depends_on:
      portainer-setup:
        condition: service_completed_successfully
