services:
  influxdb2:
    image: influxdb:2
    container_name: "${CONTAINER_NAME}"
    pull_policy: always
    ports:
      - "${INFLUXDB_PORT}:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: home
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - "${INFLUXDB_DATA}:/var/lib/influxdb2"
      - "${INFLUXDB_CONFIG}:/etc/influxdb2"
secrets:
  influxdb2-admin-username:
    file: private/.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: private/.env.influxdb2-admin-password
  influxdb2-admin-token:
    file: private/.env.influxdb2-admin-token
