name: Plex

on:
  push:
    branches: [plex]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:

env:
  MANIFEST: .github/manifest.json

jobs:
  setup-macvlan-network:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create Docker macvlan network
      run: |
        DEFAULT_INTERFACE=$(ip route show default | awk '/default/ { print $5 }' | head -1)
        SUBNET=$(ip addr show $DEFAULT_INTERFACE | grep -E 'inet [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | awk '{print $2}' | head -1)
        if [ -z "$SUBNET" ] || [ "$SUBNET" = "default" ]; then
          SUBNET="10.1.0.0/16"
          GATEWAY="10.1.0.1"
        else
          NETWORK=$(echo $SUBNET | cut -d'/' -f1 | cut -d'.' -f1-3)
          SUBNET="${NETWORK}.0/24"
          GATEWAY="${NETWORK}.1"
        fi
        docker network create -d macvlan \
          --subnet=$SUBNET \
          --gateway=$GATEWAY \
          -o parent=$DEFAULT_INTERFACE \
          macvlan-net
    
    - name: Test macvlan network with containers
      run: |
        docker run -d --name test-container \
          --network macvlan-net \
          alpine:latest sleep 300
        
        # Wait for containers to start
        sleep 5
        CONTAINER_IP=$(docker exec test-container hostname -i)
        docker stop test-container
        docker rm test-container

    
    - name: Cleanup
      if: always()
      run: |
        docker network rm macvlan-net || true
        