name: Plex

on:
  push:
    branches: [plex]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:

env:
  MANIFEST: .github/manifest.json

jobs:
  setup-macvlan-network:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Create Docker macvlan network
      run: |
        DEFAULT_INTERFACE=$(ip route show default | awk '/default/ { print $5 }' | head -1)
        SUBNET=$(ip addr show $DEFAULT_INTERFACE | grep -E 'inet [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | awk '{print $2}' | head -1)
        if [ -z "$SUBNET" ] || [ "$SUBNET" = "default" ]; then
          SUBNET="10.1.0.0/16"
          GATEWAY="10.1.0.1"
        else
          NETWORK=$(echo $SUBNET | cut -d'/' -f1 | cut -d'.' -f1-3)
          SUBNET="${NETWORK}.0/24"
          GATEWAY="${NETWORK}.1"
        fi
        docker network create -d macvlan \
          --subnet=$SUBNET \
          --gateway=$GATEWAY \
          -o parent=$DEFAULT_INTERFACE \
          macvlan-net
    
    - name: Test macvlan network with containers
      run: |
        # Create test containers on macvlan network
        echo "Creating test containers on macvlan network..."
        
        # Container 1
        docker run -d --name test-container-1 \
          --network macvlan-net \
          alpine:latest sleep 300
        
        # Container 2  
        docker run -d --name test-container-2 \
          --network macvlan-net \
          alpine:latest sleep 300
        
        # Wait for containers to start
        sleep 5
        
        echo "Container network information:"
        docker exec test-container-1 ip addr show
        docker exec test-container-2 ip addr show
    
    - name: Test network connectivity
      run: |
        # Get IP addresses of both containers
        IP1=$(docker exec test-container-1 hostname -i)
        IP2=$(docker exec test-container-2 hostname -i)
        
        echo "Container 1 IP: $IP1"
        echo "Container 2 IP: $IP2"
        
        # Test connectivity between containers
        echo "Testing connectivity from container 1 to container 2:"
        docker exec test-container-1 ping -c 3 $IP2 || echo "Ping failed - this may be expected in GitHub Actions environment"
    
    - name: Cleanup
      if: always()
      run: |
        echo "Cleaning up containers and networks..."
        docker stop test-container-1 test-container-2 test-specific-ip || true
        docker rm test-container-1 test-container-2 test-specific-ip || true
        docker network rm macvlan-net || true
        