name: Grafana

on:
  push:
    branches: [grafana]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:

env:
  MANIFEST: .github/manifest.json
  
jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/generate-env-file
        with:
          manifest: ${{ env.MANIFEST }}
          env_template: env.j2

      - uses: ./.github/actions/docker-compose-up
          
      - name: Get service url
        run: |
          GRAFANA_PORT=$(cat $MANIFEST | jq -r '.GRAFANA_PORT')
          echo "URL=http://localhost:$GRAFANA_PORT" >> $GITHUB_ENV

      - uses: ./.github/actions/test-http-response
        with:
          service_url: ${{ env.URL }}
 
      - uses: ./.github/actions/docker-compose-down
