name: Plex

on:
  push:
    branches: [plex]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:

env:
  MANIFEST: .github/manifest.json

jobs:
  setup-macvlan-network:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Create Docker macvlan network
      run: |
        DEFAULT_INTERFACE=$(ip route show default | awk '/default/ { print $5 }' | head -1)
        SUBNET=$(ip addr show $DEFAULT_INTERFACE | grep -E 'inet [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | awk '{print $2}' | head -1)
        if [ -z "$SUBNET" ] || [ "$SUBNET" = "default" ]; then
          SUBNET="10.1.0.0/16"
          GATEWAY="10.1.0.1"
        else
          NETWORK=$(echo $SUBNET | cut -d'/' -f1 | cut -d'.' -f1-3)
          SUBNET="${NETWORK}.0/24"
          GATEWAY="${NETWORK}.1"
        fi
        docker network create -d macvlan \
          --subnet=$SUBNET \
          --gateway=$GATEWAY \
          -o parent=$DEFAULT_INTERFACE \
          macvlan-net
    
    - name: Cleanup
      if: always()
      run: |
        docker network rm macvlan-net || true
        