name: Docker Compose Test

on:
  push:
    branches: [prometheus]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jinja-cli
        run: |
          pip3 install jinja-cli

      - name: Create .env
        run: |
          jinja env.j2 --data manifest.json > .env
          PROMETHEUS_CONFIG=$(cat manifest.json | jq -r '.PROMETHEUS_CONFIG')
          mkdir -p $PROMETHEUS_CONFIG
          jinja prometheus.j2 --data manifest.json > $PROMETHEUS_CONFIG/prometheus.yml

      - name: Docker Compose up
        run: |
          docker compose up -d
          
      - name: Test HTTP response
        run: |
          PROMETHEUS_PORT=$(cat manifest.json | jq -r '.PROMETHEUS_PORT')
          URL=http://localhost:$PROMETHEUS_PORT
          for i in {1..30}; do
            if curl --silent --fail $URL > /dev/null; then
              echo "Service is up!"
              break
            fi
            echo "Waiting for Service... ($i)"
            sleep 1
          done
          curl --fail $URL || (echo "Service did not respond" && exit 1)

      - name: Tear down Docker Compose
        run: docker compose down --volumes
