name: Kuma

on:
  push:
    branches: [kuma]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:


env:
  MANIFEST: .github/manifest.json

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jinja-cli
        run: |
          pip3 install jinja-cli

      - uses: ./actions/generate-env-file
        with:
          manifest: ${{ env.MANIFEST }}
          env_template: env.j2

      - name: Docker Compose up
        run: |
          docker compose up -d
          
      - name: Test HTTP response
        run: |
          kuma_port=$(cat $MANIFEST | jq -r '.kuma_port')
          URL=http://localhost:$kuma_port
          for i in {1..30}; do
            if curl --silent --fail $URL > /dev/null; then
              echo "✅ Service is up!"
              break
            fi
            echo "Waiting for Service... ($i)"
            sleep 1
          done
          curl --fail $URL || (echo "❌ Service did not respond" && exit 1)

      - name: Tear down Docker Compose
        run: docker compose down --volumes
